@startuml

left to right direction

title "Online Job Fair Registration"

actor Admin as A
actor User as U


rectangle InterviewSession {
    U -- (Register)
    (Register) -- A
    U -- (View Company)
    (View Company) -- A
    (Manage Company) -- A
    U -- (Manage Appointment)
    (Manage Appointment) -- A
}


@enduml
