@startuml

left to right direction

title "Online Job Fair Registration"

actor Admin as A
actor User as U


rectangle InterviewSession {
    U -- (Authentication)
    U -- (Register)
    (Authentication) -- A
    (Register) -- A
    U -- (View Company)
    (View Company) -- A
    (Manage Company) -- A
    U -- (Manage Interview)
    U -- (View Interview)
    (View Interview) -- A
    (Manage Interview) -- A
}


@enduml
